export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  'mailinator.com',
  'guerrillamail.com',
  '10minutemail.com',
  'tempmail.com',
  'tempmail.org',
  'throwaway.email',
  'yopmail.com',
  'sharklasers.com',
  'grr.la',
  'maildrop.cc',
  'trashmail.com',
  'discard.email',
  'mailnesia.com',
  'spamgourmet.com',
  'mytrashmail.com',
  'getnada.com',
  'temp-mail.org',
  'emailondeck.com',
  'mintemail.com',
  'guerrillamail.info',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'guerrillamail.de',
  'fakeinbox.com',
  'mohmal.com',
  'mohmal.org',
  'mailcatch.com',
  'mailpoof.com',
  'mail-tester.com',
  'trashmail.de',
  'trashmail.at',
  'mailmetrash.com',
  'sweemri.com',
  'wegwerfemail.de',
  'tempr.email',
  'dispostable.com',
  'spambox.us',
  'spambox.org',
  'spambox.me',
  'eyepaste.com',
  'bptfp.net',
  'bx6r9q.cloud',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
