-- Auto-generated content DB migration from prisma/content.prisma
-- Creates the big supplier-content tables. canonicalHotelId is a soft link
-- (no FK — it points at reference.db Hotels.id).

CREATE TABLE IF NOT EXISTS "HotelStaticContent" ("id" TEXT NOT NULL PRIMARY KEY,"provider" TEXT NOT NULL,"providerHotelId" TEXT NOT NULL,"canonicalHotelId" TEXT,"language" TEXT NOT NULL DEFAULT 'en',"name" TEXT NOT NULL,"address" TEXT,"city" TEXT,"country" TEXT,"latitude" REAL,"longitude" REAL,"starRating" REAL,"images" TEXT,"amenities" TEXT,"descriptions" TEXT,"rawPayload" TEXT,"lastSyncedAt" TEXT,"createdAt" TEXT NOT NULL DEFAULT (datetime('now')),"updatedAt" TEXT NOT NULL DEFAULT (datetime('now')),"accommodationType" TEXT,"addressLine" TEXT,"categoryCode" TEXT,"categoryName" TEXT,"chainCode" TEXT,"chainName" TEXT,"checkInTime" TEXT,"checkOutTime" TEXT,"contentHash" TEXT,"countryCode" TEXT,"countryName" TEXT,"descriptionFull" TEXT,"descriptionShort" TEXT,"email" TEXT,"facilities" TEXT,"geohash" TEXT,"minAge" INTEGER,"nearby" TEXT,"normalizedName" TEXT NOT NULL,"phone" TEXT,"policies" TEXT,"postalCode" TEXT,"propertyType" TEXT,"rooms" TEXT,"sourceUpdatedAt" TEXT,"state" TEXT,"supplierHotelCode" TEXT,"supplierHotelHid" TEXT,"supplierRegionId" TEXT,"syncErrorCode" TEXT,"syncErrorText" TEXT,"syncStatus" TEXT NOT NULL DEFAULT 'active',"website" TEXT,"primaryImageUrl" TEXT,"rawSummary" TEXT);
CREATE TABLE IF NOT EXISTS "HotelContentSyncJob" ("id" TEXT NOT NULL PRIMARY KEY,"provider" TEXT NOT NULL,"jobType" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"requestedByUserId" TEXT,"inputPayload" TEXT,"totalItems" INTEGER NOT NULL DEFAULT 0,"processedItems" INTEGER NOT NULL DEFAULT 0,"createdItems" INTEGER NOT NULL DEFAULT 0,"updatedItems" INTEGER NOT NULL DEFAULT 0,"skippedItems" INTEGER NOT NULL DEFAULT 0,"failedItems" INTEGER NOT NULL DEFAULT 0,"startedAt" TEXT,"completedAt" TEXT,"lastCursor" TEXT,"lastPage" INTEGER,"errorCode" TEXT,"errorText" TEXT,"metadata" TEXT,"logs" TEXT,"createdAt" TEXT NOT NULL DEFAULT (datetime('now')),"updatedAt" TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS "RatehawkRegionContent" ("id" TEXT NOT NULL PRIMARY KEY,"regionId" INTEGER NOT NULL,"name" TEXT NOT NULL,"parentId" INTEGER,"countryCode" TEXT,"type" TEXT,"hid" INTEGER,"hotelCount" INTEGER NOT NULL DEFAULT 0,"rawPayload" TEXT,"lastSyncedAt" TEXT NOT NULL DEFAULT (datetime('now')),"createdAt" TEXT NOT NULL DEFAULT (datetime('now')),"updatedAt" TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS "HotelContentSyncItem" ("id" TEXT NOT NULL PRIMARY KEY,"jobId" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerHotelId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"attempts" INTEGER NOT NULL DEFAULT 0,"errorCode" TEXT,"errorText" TEXT,"lastAttemptAt" TEXT,"rawSummary" TEXT,"createdAt" TEXT NOT NULL DEFAULT (datetime('now')),"updatedAt" TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS "HotelDestination" ("id" TEXT NOT NULL PRIMARY KEY,"provider" TEXT NOT NULL,"providerCode" TEXT NOT NULL,"name" TEXT NOT NULL,"countryCode" TEXT,"countryName" TEXT,"parentCode" TEXT,"type" TEXT,"latitude" REAL,"longitude" REAL,"rawPayload" TEXT,"lastSyncedAt" TEXT,"createdAt" TEXT NOT NULL DEFAULT (datetime('now')),"updatedAt" TEXT NOT NULL DEFAULT (datetime('now')));
CREATE UNIQUE INDEX IF NOT EXISTS "HotelStaticContent_provider_providerHotelId_language_key" ON "HotelStaticContent"("provider","providerHotelId","language");
CREATE UNIQUE INDEX IF NOT EXISTS "RatehawkRegionContent_regionId_key" ON "RatehawkRegionContent"("regionId");
CREATE INDEX IF NOT EXISTS "HotelContentSyncItem_jobId_idx" ON "HotelContentSyncItem"("jobId");
CREATE UNIQUE INDEX IF NOT EXISTS "HotelDestination_provider_providerCode_key" ON "HotelDestination"("provider","providerCode");
