export enum EmailTemplateKey {
  BOOKING_CREATED = 'booking.created',
  BOOKING_CONFIRMED = 'booking.confirmed',
  BOOKING_FAILED = 'booking.failed',
  BOOKING_CANCELLED = 'booking.cancelled',
  PAYMENT_FAILED = 'payment.failed',
  REFUND_COMPLETED = 'refund.completed',
  INVOICE_READY = 'invoice.ready',
  ADMIN_BOOKING_CREATED = 'admin.booking.created',
  ADMIN_BOOKING_FAILED = 'admin.booking.failed',
  ADMIN_BOOKING_CANCELLED = 'admin.booking.cancelled',
  ADMIN_PAYMENT_RECEIVED = 'admin.payment.received',
  PASSWORD_RESET_REQUESTED = 'password.reset.requested',
  PASSWORD_RESET_CONFIRMED = 'password.reset.confirmed',
  PASSWORD_CHANGED = 'password.changed',
  TEST_EMAIL = 'test.email',
  AGENT_INVITE = 'agent.invite',
  DEMO_VERIFY_EMAIL = 'demo.verify.email',
  DEMO_CREDENTIALS = 'demo.credentials',
  ADMIN_DEMO_LEAD = 'admin.demo.lead',
}
