export enum PaymentStatus {
  PENDING = "PENDING",

  PROCESSING = "PROCESSING",

  REQUIRES_ACTION = "REQUIRES_ACTION",

  AUTHORIZED = "AUTHORIZED",

  PAID = "PAID",

  FAILED = "FAILED",

  CANCELLED = "CANCELLED",

  REFUNDED = "REFUNDED",
}